version: "3.8"

services:
  db: 
    image: postgres:14

    container_name: db-postgres

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRESS_PASSWORD}

    ports:
      - "5432:5432"
